<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>

<head>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Plataforma de Desarrollo de Software</title>
<link href='http://fonts.googleapis.com/css?family=Bad+Script' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Bad+Script|Cinzel+Decorative' rel='stylesheet' type='text/css'>
<link type="text/css" href="/styles/960_16_col.css" rel="stylesheet"/>
<link type="text/css" href="/styles/estilos_evidencias.css"rel="stylesheet"/>

</head>
<body class="evi fondo">
	<div class="container_16">	
	<div class="grid_1 evi logo_evidencia size_logo">
	</div>
		<div class="top_12">
		
				<h1 class="evi letra_principal evi logo evidencia  push_4 top_8 ">Plataforma de Desarrollo de
					Software</h1>
					
					
	</div>
	
	<div class="grid_1">
		<div id="menu">
		<a class="evi letra_menu">menu </a>

			<ul>
				<li class="nivel1"><a class="nivel1 proyectos" href="/index.php/index/repro">Proyectos</a>
				
				</li>
				
				<li class="nivel1"><a class="nivel1 desarrolladores" href="/index.php/index/desarrollador">Desarrolladores</a>
				
				<li class="nivel1"><a class="nivel1 recursos" href="/index.php/index/recursos">Recursos</a>
				</li>
				<li class="nivel1"><a class="nivel1 versiones" href="/index.php/index/addversion">Versiones</a>
				</li>
				
				<li class="nivel1"><a class="nivel1 clientes" href="/index.php/index/addcliente">Clientes</a>
				</li>				
				
								
				<li class="nivel1"><a class="nivel1 automatizacion" href="/index.php/index/addshell">Automatizacion</a>
				</li>
				</ul>
				
				</div>
	
	</div>
	
	<div class="grid_1 push_4 top_18">
	<?php echo $this->layout()->content; ?>
	</div>
	
</div>

</div>
</body>
</html>