<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<link type="text/css" href="public/styles/960_16_col.css" rel="stylesheet">
<link type="text/css" href="public/styles/estilos_evidencias" rel="stylesheet">
</head>
<body>
	<div id="main-container">

		<div id="form-container">
		<h1>Clientes</h1>
			<h2>REGISTRAR CLIENTES</h2>
			<?php  echo $this->frmcliente;?>
			<a href="/index.php/index/consulta-clien/">Ver Clientes</a>


		</div>
	</div>

</body>
</html>