<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
 <link rel="stylesheet" href="styles/nivo-slider.css" type="text/css" media="screen" /> <!-- carga estilo nivo-slider.css -->
<link rel="stylesheet" href="styles/default.css" type="text/css" media="screen" /> <!-- carga estilo theme default.css -->
<script src="js/jquery-1.9.0.min.js" type="text/javascript"></script> <!-- carga jQuery -->
<script src="js/jquery.nivo.slider.pack.js" type="text/javascript"></script> <!-- carga plugin jquery.nivo.slider.pack.js -->
<script type="text/javascript">
    $(window).load(function() {
            $('#slider').nivoSlider(); // Carga de NivoSlider
    });
  
  </script
  
</head>
<body>

  <!-- ><h1>An error occurred</h1>
  <h2><?php echo $this->message ?></h2>

  <?php if (isset($this->exception)): ?>
  
  <h3>Exception information:</h3>
  <p>
      <b>Message:</b> <?php echo $this->exception->getMessage() ?>
  </p>

  <h3>Stack trace:</h3>
  <pre><?php echo $this->exception->getTraceAsString() ?>
  </pre>

  <h3>Request Parameters:</h3>
  <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
  </pre>

  <?php endif ?>
  
-->
  
  
    
  <div id="wrapper">
  <div class="slider-wrapper theme-default">
  <div id="slider" class="nivoSlider">
  
  
  <img alt="" src="imagenes/Desarrollo.jpg" title="Mysql y Java, son las Aplicaciones mas importantes en la ingenieria de <br>Desarrollo de software">
  <a href="http://web.trucos.com">
  <img alt="" src="imagenes/desarrollo3.jpg" title="Diferentes aplicaciones para el desarrollo de software<br>como son PHP,ZF,HTML,JQUERY,CSS"
  
  />
  </a>
  <img alt="" src="imagenes/desarrollo6.jpg" data-transition="slideInLeft" title="Etapas del desarrollo de software"/>
  <img alt="" src="imagenes/desarrollo8.jpg" title="La importancia que lleva el desarrollar un software de eficiencia y de exelencia calidad"/>
  <img alt="" src="imagenes/software.jpg" title="Develoment the Sofware">
  </div>
  </div>
  </div>
  
  
</body>
</html>
